from pymongo import MongoClient

client = MongoClient('localhost:27017')
db_name = client['citybik']
collection_name = db_name['bikestations']

pipeline = [
    {
        '$match': {}
    },
    {
        '$project': {
            '_id': 0, # Exclude the ID auto-generated by Mongo to avoid confusion
            'id': 1,
            'name': 1,
            'timestamp': 1,
            'free_bikes': 1,
            'empty_slots': 1,
            # FALTA Subconsulta para uid, last_updated, slots, normal_bikes, ebikes
        }
    }
]

result = collection_name.aggregate(pipeline)
for document in result:
    print(document)