from pymongo import MongoClient
import pandas as pd

# Conection to the database
client = MongoClient('localhost:27017')
db_name = client['citybik']
collection_name = db_name['bikestations']

# Aggregation pipeline
pipeline = [
    {
        '$match': {}
    },
    {
        '$project': {
            '_id': 0, # Exclude the ID auto-generated by Mongo to avoid confusion
            'id': 1,
            'name': 1,
            'timestamp': 1,
            'free_bikes': 1,
            'empty_slots': 1,
            # With this syntax, the columns of the subcollection will show in separated columns
            'uid': '$extra.uid',
            'last_updated': '$extra.last_updated',
            'slots': '$extra.slots',
            'normal_bikes': '$extra.normal_bikes',
            'ebikes': '$extra.ebikes',
        }
    }
]

result = list(collection_name.aggregate(pipeline)) # convert the cursor returned by aggregate() to make it compatible with pandas dataframes
df = pd.DataFrame(result)
# Export to csv and parquet, excluding the index of the dataframe
df.to_csv('../data/bike_stations_in_Corunha.csv', index = False)
df.to_parquet('../data/bike_stations_in_Corunha.parquet', index = False)

for document in result:
    print(document)